version: '2'
volumes:
  node_modules:
secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa
  user_ssh_known_hosts:
    file: ~/.ssh/known_hosts
services:
  ember:
    image: danlynn/ember-cli:4.1.1
    volumes:
      - .:/myapp
      - .bash_history:/root/.bash_history
    tmpfs:
      - /myapp/tmp
    ports:
      - '4200:4200'
    secrets:
      - user_ssh_key
      - user_ssh_known_hosts
  test:
    image: danlynn/ember-cli:4.1.1
    command: ember test --server
    volumes:
      - .:/myapp
    tmpfs:
      - /myapp/tmp
    ports:
      - '7020:7020'
      - '7357:7357'
